version: "3.3"

services:
    mysql:
        container_name: "db"
        image: mysql
        environment:
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "demo"
            MYSQL_ROOT_PASSWORD: "demo"
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - my-db:/var/lib/mysql

    redis:
        image: redis:6.2-alpine
        ports:
            - "6379:6379"
        command: redis-server --save 60 1
volumes:
    my-db:
